workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: default
      vars:
        BUNDLE_ID: "com.aitechapps.fitnesschallenge"
      
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Install dependencies
        script: | 
          flutter pub get
          cd ios && pod install --repo-update && cd ..

      - name: Run widget tests
        script: flutter test
        ignore_failure: false
          
      - name: Run Flutter build
        script: | 
          flutter build ios --release --no-codesign

      - name: Run Crashlytics dSYM upload
        script: | 
          chmod +x ios_crashlytics.sh
          ./ios_crashlytics.sh

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        submit_to_testflight: true
        submit_to_app_store: false
