workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: default
      vars:
        BUNDLE_ID: "com.aitechapps.fitnesschallenge" # <-- replace with your app’s bundle ID
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # Add in Codemagic UI
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...) # Add in Codemagic UI
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # Add in Codemagic UI

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..

      - name: Run Flutter build
        script: |
          flutter build ios --release --no-codesign

      - name: Run Crashlytics dSYM upload
        script: |
          chmod +x ios_crashlytics.sh
          ./ios_crashlytics.sh

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    integrations:
      app_store_connect:
        # Replace this with the integration ID from Codemagic UI
        id: Q78YG2L77B

    publishing:
      app_store_connect:
        auth: integration   # ✅ tells Codemagic to use the integration you linked in the UI
        submit_to_testflight: true
        submit_to_app_store: false

