workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: default
      vars:
        BUNDLE_ID: "com.aitechapps.fitnesschallenge"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(81559dfb-0211-4029-ad4e-cf460b38f18a) # <-- Put your App Store Connect Issuer Id here
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Q78YG2L77B) # <-- Put your App Store Connect Key Identifier here
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(-----BEGIN PRIVATE KEY-----MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDwFZJLj6BSF8nyavjMMmoT4XDIvVkS+gbCUEkd0EhvCgCgYIKoZIzj0DAQehRANCAARFtVkLXUbFrbkAKKr62EpVG9mUdckpK7HD0oi8Cmmq0hLpZy8LO9chmGR6wOQlRDMBMV2APoIASbqC6s2Exhn9-----END PRIVATE KEY-----)

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Install dependencies
        script: | 
          flutter pub get
          cd ios && pod install --repo-update && cd ..

      - name: Run widget tests
        script: flutter test
        ignore_failure: false
          
      - name: Run Flutter build
        script: | 
          flutter build ios --release --no-codesign

      - name: Run Crashlytics dSYM upload
        script: | 
          chmod +x ios_crashlytics.sh
          ./ios_crashlytics.sh

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        submit_to_testflight: true
        submit_to_app_store: false
